### ISSUE TITLE
Instances aren't rendered

### ISSUE THREAD

**Issue by jweyrich** [fudgepop01/kaitai_ide_vscode#6]
It doesn't seem to support `instances` as per https://doc.kaitai.io/user_guide.html#_instances_data_beyond_the_sequence

You can reproduce the issue using [microsoft_pe.ksy](https://github.com/kaitai-io/kaitai_struct_formats/blob/master/executable/microsoft_pe.ksy) and trying to visualize any .exe or .dll file.
The instance defined at [line 24](https://github.com/kaitai-io/kaitai_struct_formats/blob/master/executable/microsoft_pe.ksy#L24) doesn't get rendered.

**Comment by fudgepop01** [comment]
Hello! Thanks for the bug report. I apologize for not getting back to you in a timely manner, for some reason my github notifications are all over the place.

As for what I _think_ is going on:

To prevent extremely large files from crashing or hanging due to overuse of memory, by-default I have a setting called "eager analysis?" turned off. This can be toggled in the settings panel on the side of the visualizer. This panel can be toggled by clicking on the vertical bar that says "settings" on the right side of the viewer:
![image](https://user-images.githubusercontent.com/3662774/85927011-4e23b680-b871-11ea-9cc5-b19816d95616.png)

When not in eager mode, the parser will detect instances and prevent them from automatically getting rendered without user interaction. To actually render these instances while not in eager mode, you'll need to click on it over in the `KSEXPLORER` panel and expand its tree-view:
![image](https://user-images.githubusercontent.com/3662774/85927093-e1f58280-b871-11ea-9cd2-f00ff3fa0aa0.png)

This will apply to any instance, including instances that are children of other instances.

Once eager mode is enabled, everything is parsed by default other than circular structures, which are handled in the same way (click on them in the tree view to render them in the viewer). 

---

In hindsight, the README isn't very clear about how that works or how to access the settings in the first place. I'll update it to accommodate the changes I made to it a few months ago. 

Thanks again for the report, I hope this helped!

**Comment by jweyrich** [comment]
Oh, the lazy loading works as you suggested using the ksexplorer/navigator. Not sure how I didn't notice its existence before. Thank you!
